TEST 1 Output
T = 20
--------------------------
Computing integral images
4.899651050567627 seconds
Building features
0.4159691333770752 seconds
Applying features to training examples
2169.0448591709137 seconds
Selecting best features
Selected 5171 potential features
Trained 1000 classifiers out of 5171
Trained 2000 classifiers out of 5171
Trained 3000 classifiers out of 5171
Trained 4000 classifiers out of 5171
Trained 5000 classifiers out of 5171
-> exited with following error (FIXED NOW):
	Traceback (most recent call last):
  File "face_detection.py", line 56, in <module>
    main()
  File "face_detection.py", line 52, in main
    train_viola(20)
  File "face_detection.py", line 11, in train_viola
    clf.train(training, 2429, 4548)
  File "/Users/andrewopem/Desktop/EE_451/project/Viola-Jones/serial_v2/viola_jones.py", line 63, in train
    weights = update_weights(weights, accuracy, beta)
	NameError: name 'update_weights' is not defined